"use client";

import { Activity, ArrowRight, BrainCircuit, ChevronRight, Database, FileCheck2, MoreHorizontal, Sparkles, TimerReset } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { cn } from "@/lib/utils";
import { type Locale, pick } from "@/lib/onelearn/i18n";
import type { LearnerIdentity, LearnerStats, MasteryOverview, View } from "./types";
import { MetricCard } from "./ui";

export function Dashboard({ onNavigate, locale, identity, stats, storage, mastery }: { onNavigate: (view: View) => void; locale: Locale; identity: LearnerIdentity | null; stats: LearnerStats | null; storage: "durable" | "ephemeral"; mastery: MasteryOverview | null }) {
  const l = (zh: string, en: string) => pick(locale, zh, en);
  const pathMastery = mastery?.summary.pathMastery ?? 0;
  const dueItems = mastery?.due.slice(0, 3) ?? [];
  const focus = mastery?.records.filter((record) => !record.mastered).sort((a, b) => a.score - b.score)[0] ?? null;
  const weekly = mastery?.weekly ?? [];
  const maxWeekly = Math.max(1, ...weekly.map((day) => day.count));
  const weekTotal = weekly.reduce((sum, day) => sum + day.count, 0);
  const recent = mastery?.recent ?? [];
  const eventLabel = (type: string) => type === "review_completed" ? l("复习", "Review") : type === "tutor_turn" ? l("导师", "Tutor") : l("练习", "Practice");
  const formatTime = (seconds: number) => new Date(seconds * 1000).toLocaleString(locale === "zh" ? "zh-CN" : "en-US", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" });
  const missionSteps: Array<[string, View]> = [[l("学习讲解并回答导师", "Study and answer the tutor"), "learn"], [l("独立完成练习", "Pass practice unassisted"), "practice"], [l("隔天复习验证", "Verify with a delayed review"), "review"]];
  const missionStep = !focus ? 0 : focus.unassistedPasses === 0 ? 1 : 2;
  return <div className="space-y-7 animate-in fade-in duration-500">
    <section className="dashboard-hero">
      <div className="relative z-10 max-w-2xl"><div className="eyebrow"><Sparkles className="size-3.5" />{storage === "durable" ? l("跨设备学习档案已同步", "CROSS-DEVICE PROFILE SYNCED") : l("设备模式 · 登录后跨设备同步", "DEVICE MODE · SIGN IN TO SYNC")}</div><h1>{l(`你好，${identity?.displayName ?? "学习者"}。`, `Hello, ${identity?.displayName ?? "learner"}.`)}</h1><p>{l("课程、资料、练习和 AI 导师证据现在进入同一份学习档案。", "Courses, sources, practice, and AI tutor evidence now flow into one learning profile.")}</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={() => onNavigate("learn")} className="primary-pill">{l("继续学习", "Continue learning")} <ArrowRight /></Button><Button onClick={() => onNavigate("path")} variant="outline" className="secondary-pill">{l("查看知识地图", "View knowledge map")}</Button></div></div>
      <div className="mastery-orbit" aria-label={l(`当前路径掌握度 ${pathMastery}%`, `Current path mastery ${pathMastery} percent`)}><div className="orbit-ring orbit-ring-one" /><div className="orbit-ring orbit-ring-two" /><div className="orbit-core"><strong>{pathMastery}%</strong><span>{l("路径掌握度", "PATH MASTERY")}</span></div><i className="orbit-node node-a" /><i className="orbit-node node-b" /><i className="orbit-node node-c" /></div>
    </section>
    <section className="grid grid-cols-2 gap-3 xl:grid-cols-4"><MetricCard label={l("课程版本", "Course versions")} value={String(stats?.courseVersions ?? 0)} detail={l("跨设备保存", "saved across devices")} icon={BrainCircuit} /><MetricCard label={l("学习事件", "Learning events")} value={String(stats?.learningEvents ?? 0)} detail={l("课程、练习与导师", "courses, practice, and tutor")} icon={Activity} /><MetricCard label={l("平均质量", "Average quality")} value={`${Math.round(stats?.averageQuality ?? 0)}%`} detail={l("AI 独立评测", "independent AI review")} icon={FileCheck2} /><MetricCard label={l("可信资料", "Trusted sources")} value={String(stats?.sources ?? 0)} detail={l("已进入检索知识库", "indexed for retrieval")} icon={Database} /></section>
    <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <article className="surface-card p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="section-kicker">{l("今日任务", "TODAY'S MISSION")}</div><h2 className="mt-2 text-xl font-medium tracking-tight text-white">{focus ? focus.nodeTitle : l("开始第一节课", "Start your first lesson")}</h2><p className="mt-1 text-sm text-slate-400">{focus ? l(`当前掌握度 ${focus.score}% · 已独立答对 ${focus.unassistedPasses} 次`, `Mastery ${focus.score}% · ${focus.unassistedPasses} unassisted passes`) : l("生成课程并开始练习后，这里会显示你最需要加强的节点。", "Generate a course and practice; your weakest node will appear here.")}</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{missionSteps.map(([item, target], i) => <button key={item} onClick={() => onNavigate(target)} className={cn("mission-step text-left", i === missionStep && "is-current")}><div className="flex items-center gap-2"><span>{i + 1}</span><p>{item}</p></div></button>)}</div><div className="mt-6 flex items-center gap-3"><Progress value={focus?.score ?? 0} className="h-1.5 bg-white/8 [&>div]:bg-cyan-300" /><span className="text-xs text-slate-500">{focus?.score ?? 0}%</span></div></article>
      <article className="surface-card flex min-h-[260px] flex-col p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="section-kicker">{l("复习队列", "REVIEW QUEUE")}</div><h2 className="mt-2 text-lg font-medium text-white">{l(`${mastery?.summary.due ?? 0} 个节点待复习`, `${mastery?.summary.due ?? 0} nodes due`)}</h2></div><TimerReset className="size-5 text-amber-300" /></div><div className="mt-5 space-y-2">{dueItems.length ? dueItems.map((item) => <button key={`${item.courseVersionId}:${item.nodeKey}`} onClick={() => onNavigate("review")} className="review-row"><span className={cn("review-priority", item.retention < 60 ? "high" : "normal")} /><span className="flex-1 text-left text-sm text-slate-200">{item.nodeTitle}</span><span className="text-xs text-slate-500">{l(`保持率 ${item.retention}%`, `${item.retention}% retained`)}</span><ChevronRight className="size-4 text-slate-600" /></button>) : <p className="text-sm text-slate-500">{l("暂时没有到期的复习。", "Nothing is due for review yet.")}</p>}</div><Button onClick={() => onNavigate("review")} variant="ghost" className="link-button mt-auto">{l("打开复习队列", "Open review queue")} <ArrowRight /></Button></article>
    </section>
    <section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]">
      <article className="surface-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="section-kicker">{l("学习证据", "LEARNING EVIDENCE")}</div><h2 className="mt-2 text-lg font-medium text-white">{l("最近 7 天", "Last 7 days")}</h2></div><span className="text-sm text-emerald-300">{weekTotal}</span></div><div className="velocity-chart" aria-label={l("最近 7 天学习证据数量", "Learning evidence over the last 7 days")}>{weekly.map((day) => <div key={day.day} className="chart-column"><i style={{ height: `${Math.max(4, Math.round((day.count / maxWeekly) * 100))}%` }} /><span>{new Date(`${day.day}T00:00:00Z`).toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US", { weekday: "narrow", timeZone: "UTC" })}</span></div>)}</div></article>
      <article className="surface-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="section-kicker">{l("学习轨迹", "LEARNING TRACE")}</div><h2 className="mt-2 text-lg font-medium text-white">{l("最近的能力证据", "Recent evidence")}</h2></div><MoreHorizontal className="size-4 text-slate-600" /></div><div className="mt-5 divide-y divide-white/6">{recent.length ? recent.slice(0, 5).map((item, i) => <div key={`${item.createdAt}-${i}`} className="grid grid-cols-[92px_1fr_auto] items-center gap-3 py-3.5"><span className="text-xs text-slate-600">{formatTime(item.createdAt)}</span><div><p className="text-sm text-slate-200">{item.lessonTitle ?? l("学习节点", "Learning node")}</p><p className="text-xs text-slate-500">{eventLabel(item.eventType)}</p></div><span className="text-xs text-cyan-300">{item.correct === null ? l("已记录", "Recorded") : item.correct ? l("答对", "Correct") : l("答错", "Missed")}</span></div>) : <p className="py-4 text-sm text-slate-500">{l("完成练习或与导师对话后，证据会出现在这里。", "Evidence appears here after practice or tutor sessions.")}</p>}</div></article>
    </section>
  </div>;
}
